spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/scriptorium_db?preferQueryMode=extended
    username: postgres
    password: your_actual_password
    driver-class-name: org.postgresql.Driver
  security:
    user:
      name: admin
      password: admin123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      # Commented out to avoid warnings with Hibernate 6+
      # dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG
