spring:
  datasource:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 10000
      max-lifetime: 30000
    url: jdbc:postgresql://dpg-cu7bvg5svqrc7397mv50-a.singapore-postgres.render.com:5432/scriptorium_db
    username: scriptorium_db_user
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  security:
    user:
      name: admin
      password: admin123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${PORT:8080}  #This tells Spring Boot to use the PORT environment variable provided by Render. If the variable is not set (e.g., when running locally), it will fall back to port 8080.



#logging:
#  file:
#    name: logs/application.log
#  level:
#    com.example.scriptorium_api.config.SecurityConfig: INFO

logging:
  level:
    org:
      springframework:
        security: DEBUG


